include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  exclude:
    - lib/gen/*
linter:
  rules:
    public_member_api_docs: false
    overridden_fields: false # flame conventions require this on occasion